#!/bin/bash

#code script to take 2 arguments and print out something if you don't get two positional parameters

# error checking
if [ $# -ne 2 ]; then
    echo "please enter 2 parameters after $0"
    exit 0
fi

# take 2 arguments
num1=$1
num2=$2

#Maths
sum=$(($num1 + $num2))

echo "Your answer to your math question is $sum"