#!/bin/bash
# echo "please tell me your first and last name:"
# read first_name last_name
# echo "Nice to meet you $first_name $last_name"


read -p "Enter your favorite colour (default is blue): " colour
echo "Your favorite colour is $colour."