#!/bin/bash

#script can run handling multiple spaces now

source_file=$1
shift

copied_file=""
while (( "$#" )); do
  copied_file="${copied_file}${1}"
  shift
done

cp "$source_file" "${source_file}${copied_file}"
