#!/bin/bash

#test aws-cli
aws --version > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "AWS-CLI not installed please install first then run $0"
    exit 1
else
    echo "AWS-CLI installed and configured... running script"
    echo ""
fi  

#run s3 bucket list
aws s3 ls
echo ""
echo "Which bucket would you like to upload the file to? "
read s3_bucket_name

#Check and add the "s3://" prefix if it's not already there
if [[ "$s3_bucket_name" != s3://* ]]; then
    s3_bucket_name="s3://$s3_bucket_name"
fi
echo ""

#select folder to sync the cloud
file_path=$1

if [ -e $file_path ]; then
    aws s3 cp $file_path $s3_bucket_name
    echo ""
    echo "---printing out s3 bucket files---"
    aws s3 ls $s3_bucket_name
else
    echo "file not found"
    echo "run $0 again after checking file"
fi


#error handling:
#if signed into invalid account but choose a valid file name it will still output "file uploaded"
